services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "mydatabase"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net 
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    # export from container t
    ports:
      - "5672:5672" #AMQP protocol port
      - "15672:15672" #management UI port
    networks:
      - app-net
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    depends_on:
      - rabbitmq
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME : "mydatabase"
      RABBITMQ_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_PASS: "${RABBITMQ_DEFAULT_PASS}"
      
  worker:
    build: ./worker
    depends_on:
      - mongo
      - rabbitmq
      - scheduler
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "mydatabase"



volumes:
  mongo-data:

networks:
  app-net:
