apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ipa2025-msapp-worker-scaler
  namespace: ipa2025
spec:
  scaleTargetRef:
    name: ipa2025-msapp-worker
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        queueName: router_jobs
        mode: QueueLength
        value: "10"
        protocol: auto
        host: amqp://admin:rabbitmq@192.168.239.151:5672/
        usernameFromEnv: RABBITMQ_DEFAULT_USER
        passwordFromEnv: RABBITMQ_DEFAULT_PASS